name: CICD

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    
    - name: Install dependencies
      run: npm i

    - name: Gatsby Publish
      run: | 
        git config --global user.email nathaliemarquesin@gmail.com
        git config --global user.name Nathalie
        npm run deploy
      
