name: CICD

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2
      
    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        name: 'Nathalie'
        email: 'nathaliemarquesin@gmail.com'
        actor: 'risbakk'
        token: '${{ secrets.ACCESS_TOKEN }}'
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    
    - name: Install dependencies
      run: npm i

    - name: Gatsby Publish
      run: npm run deploy
