name: CICD

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2
 
    - name: Gatsby Publish
      uses: risbakk/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        deploy-repo: "https://github.com/risbakk/risbakk.github.io"
